### ISSUE TITLE
min_temp:-60 makes no sense and disables a safety feature

### ISSUE THREAD

**Issue by sprior** [mypeopoly/magneto-x-klipper-config#3]
If the hot end thermister is completely broken most printers will read it as -20C, so setting min_temp = -60 seems like a completely insane value.  The min_temp and max_temp values define a "sane" range of values and any reading outside of that range indicates an "insane" value which for safety reasons shuts the printer down immediately.  So you certainly want a min_temp low enough that the printer isn't going to be sitting in a cold room and refuses to start, but I'm pretty sure NOBODY that has their printer in -60C has 3D printing on their minds.

I understand that Klipper will still check to make sure it sees the change in temp over time that it expects and if the thermistor is disconnected it won't see that, but the min/max temp range should still be set reasonably.

All of this applies to both the hotend and bed heaters.

**Comment by mypeopoly** [comment]
Thanks for the suggestion, it has been modified

**Comment by sprior** [comment]
@mypeopoly  I think you missed a nuance in your fix, -20 is still within the allowed range so it still won't work.  You probably want to change it to -10 (which is still below freezing).  Personally I'd make it 10.
